# Generated by Django 5.2.7 on 2026-03-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('target_audience', models.CharField(help_text='مثلاً: أصحاب المحلات، النساء المهتمات بالجمال', max_length=255)),
                ('benefits', models.TextField(help_text='شنو هي الفوائد الأساسية؟')),
                ('problem_solved', models.TextField(help_text='شنو هو المشكل اللي كيهني منو العميل؟')),
                ('common_objections', models.TextField(blank=True, help_text='الاعتراضات (الثمن غالي، التوصيل...) وردودها')),
                ('faq_context', models.TextField(blank=True, help_text='معلومات تقنية (الضمان، مدة التوصيل، طرق الدفع)')),
            ],
        ),
    ]
