# Generated by Django 5.2.7 on 2026-03-20 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('automations', '0001_initial'),
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_sent', models.TextField()),
                ('client_response', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('delivered', 'Delivered'), ('replied', 'Replied'), ('interested', 'Interested'), ('purchased', 'Purchased')], default='sent', max_length=20)),
                ('link_clicked', models.BooleanField(default=False)),
                ('ai_sentiment', models.CharField(blank=True, help_text='تحليل رد العميل (إيجابي/سلبي)', max_length=50)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('response_at', models.DateTimeField(blank=True, null=True)),
                ('automation', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='automations.automation')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clients.client')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product')),
            ],
        ),
    ]
