# Generated by Django 5.2.7 on 2026-03-20 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Automation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('trigger_type', models.CharField(choices=[('after_signup', 'After Signup'), ('after_purchase', 'After Purchase'), ('inactive_reminder', 'Inactive Reminder'), ('cart_abandoned', 'Cart Abandoned')], max_length=50)),
                ('message_template', models.TextField(help_text='القالب الأساسي للرسالة')),
                ('delay_hours', models.PositiveIntegerField(default=0)),
                ('working_hours_start', models.TimeField(default='09:00')),
                ('working_hours_end', models.TimeField(default='22:00')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
