# Generated by Django 5.2.7 on 2026-03-29 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_alter_client_options_remove_client_last_purchase_and_more'),
        ('products', '0002_alter_product_options_remove_product_benefits_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, editable=False, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='clients.client')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ventes', to='products.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
