# Generated by Django 5.2.7 on 2026-03-31 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vente',
            options={},
        ),
    ]
