# Generated by Django 5.2.7 on 2026-03-31 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventes', '0002_alter_vente_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vente',
            options={'ordering': ['-created_at']},
        ),
    ]
