"""
Django settings for EcomFlow_CRM project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os, sys
import dj_database_url  # <-- (تمت الإضافة) للتعامل مع قاعدة البيانات
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# إعدادات الأمان (يتم قراءتها من ملف .env إذا توفرت)
# ==============================================================================
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# السماح لجميع الروابط مؤقتاً لتسهيل النشر
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# ==============================================================================
# التطبيقات المثبتة
# ==============================================================================
INSTALLED_APPS = [
    'cloudinary_storage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    
    # (تمت الإضافة) تطبيقات Cloudinary يجب أن تكون قبل staticfiles
    
    'django.contrib.staticfiles',
    'cloudinary',

    # تطبيقات مشروعك
    'apps.clients',
    
   
    'apps.ventes',
    'apps.accounts',
    'apps.dashboard',
    'apps.products',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # (تمت الإضافة) ضغط وتسريع الملفات الثابتة
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EcomFlow_CRM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EcomFlow_CRM.wsgi.application'

# ==============================================================================
# قاعدة البيانات (Database)
# ==============================================================================
# العمل بـ SQLite محلياً فقط على الجهاز
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ==============================================================================
# التحقق من كلمات المرور
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================================================
# اللغة والمنطقة الزمنية
# ==============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==============================================================================
# الملفات الثابتة (Static Files)
# ==============================================================================
# 1. الرابط الذي يظهر في المتصفح
STATIC_URL = 'static/'

# 2. المجلد الذي تضع فيه ملفاتك يدوياً أثناء البرمجة (تأكد أن اسمه static في مشروعك)
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# 3. المجلد الذي سيجمع فيه ديجانغو الملفات عند تشغيل أمر collectstatic
# يجب أن يكون اسمه مختلفاً، مثلاً 'staticfiles'
STATIC_ROOT = BASE_DIR / "staticfiles"

# 4. إعدادات WhiteNoise (يفضل استخدام النسخة الأحدث التي لا تسبب مشاكل في التطوير)
STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# ==============================================================================
# ملفات الميديا والصور (Media Files & Cloudinary)
# ==============================================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# (تمت الإضافة) توجيه الصور لتُحفظ في Cloudinary
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# سيتم جلب بيانات كلاوديناري من ملف .env لاحقاً
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# ==============================================================================
# إعدادات المستخدم وتسجيل الدخول
# ==============================================================================
AUTH_USER_MODEL = 'accounts.User'

LOGIN_REDIRECT_URL = 'clients:list'
LOGOUT_REDIRECT_URL = 'accounts:login'