"""
Django settings for EcomFlow_CRM project.

Generated by 'django-admin startproject' using Django 5.2.7.
"""

from pathlib import Path
import os, sys
import dj_database_url  # <-- (تمت الإضافة) للتعامل مع قاعدة البيانات
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ==============================================================================
# إعدادات الأمان (يتم قراءتها من ملف .env إذا توفرت)
# ==============================================================================
SECRET_KEY = os.getenv('SECRET_KEY')
DEBUG = os.getenv('DEBUG', 'False') == 'True'

# السماح لجميع الروابط مؤقتاً لتسهيل النشر
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# ==============================================================================
# التطبيقات المثبتة
# ==============================================================================
INSTALLED_APPS = [
    'cloudinary_storage',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    
    # (تمت الإضافة) تطبيقات Cloudinary يجب أن تكون قبل staticfiles
    
    'django.contrib.staticfiles',
    'cloudinary',

    # تطبيقات مشروعك
    'apps.clients',
    'apps.products',
    'apps.automations',
    'apps.ventes',
    'apps.accounts',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware', # (تمت الإضافة) ضغط وتسريع الملفات الثابتة
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'EcomFlow_CRM.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'EcomFlow_CRM.wsgi.application'


# ==============================================================================
# قاعدة البيانات (Database)
# ==============================================================================
# (تم التعديل) سيعمل بـ SQLite على جهازك، وسيعمل بـ PostgreSQL على الإنترنت تلقائياً
DATABASES = {
    'default': dj_database_url.config(
        default=f"sqlite:///{BASE_DIR / 'db.sqlite3'}",
        conn_max_age=600 ,
        conn_health_checks=True,
    )
}


# ==============================================================================
# التحقق من كلمات المرور
# ==============================================================================
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ==============================================================================
# اللغة والمنطقة الزمنية
# ==============================================================================
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True


# ==============================================================================
# الملفات الثابتة (Static Files)
# ==============================================================================
STATIC_URL = 'static/'
# المسار الذي سيجمع فيه ديجانغو كل ملفات التصميم استعداداً للرفع
STATIC_ROOT = BASE_DIR / 'staticfiles'
# إخبار WhiteNoise بضغط الملفات لتسريع الموقع
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# ==============================================================================
# ملفات الميديا والصور (Media Files & Cloudinary)
# ==============================================================================
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# (تمت الإضافة) توجيه الصور لتُحفظ في Cloudinary
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# سيتم جلب بيانات كلاوديناري من ملف .env لاحقاً
CLOUDINARY_STORAGE = {
    'CLOUD_NAME': os.getenv('CLOUDINARY_CLOUD_NAME'),
    'API_KEY': os.getenv('CLOUDINARY_API_KEY'),
    'API_SECRET': os.getenv('CLOUDINARY_API_SECRET'),
}

# ==============================================================================
# إعدادات المستخدم وتسجيل الدخول
# ==============================================================================
AUTH_USER_MODEL = 'accounts.User'

LOGIN_REDIRECT_URL = 'clients:list'
LOGOUT_REDIRECT_URL = 'accounts:login'