# Generated by Django 5.2.7 on 2026-03-26 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='client',
            name='last_purchase',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.RemoveField(
            model_name='client',
            name='total_orders',
        ),
        migrations.RemoveField(
            model_name='client',
            name='total_spent',
        ),
    ]
